### ISSUE TITLE
login semplificato per selezione ownerId

### ISSUE THREAD

**Issue by micnori** [smartcommunitylab/sco.climb.driverapp#6]
implementare una versione semplificata di login per accedere a ownerId e token per le chiamate REST

**Comment by oskarnrk** [comment]
- [ ] Aggiungere pagina (la prima del wizard) per selezionare IDENTITY
- [ ] Salvare indice IDENTITIES in localStorage
- [ ] Voce menu per logout (cancella indice da localStorage)
