### ISSUE TITLE
revisione pannelli liste bambini

### ISSUE THREAD

**Issue by micnori** [smartcommunitylab/sco.climb.driverapp#7]
adattare i pannelli delle due liste bambini ("onboard" e "della fermata") a vari schermi.
Come semplificazione possiamo fissare la dimensione delle immagini e della lista "on board" in altezza

**Comment by oskarnrk** [comment]
Per ora manteniamo il numero di elementi su ogni riga (3).

**Comment by micnori** [comment]
usiamo il mitico plugin del browser uguale per tutti :)

**Comment by micnori** [comment]
ionic browser add crosswalk

**Comment by micnori** [comment]
ionic browser list

ionic browser add crosswalk@10.39.235.15 (add specific version)

**Comment by micnori** [comment]
ionic plugin add cordova-plugin-crosswalk-webview
